package com.iridium.iridiumfactions.configs;

import com.iridium.iridiumfactions.commands.*;

public class Commands {
    public CreateCommand createCommand = new CreateCommand();
    public HelpCommand helpCommand = new HelpCommand();
    public ReloadCommand reloadCommand = new ReloadCommand();
    public InviteCommand inviteCommand = new InviteCommand();
    public UnInviteCommand unInviteCommand = new UnInviteCommand();
    public JoinCommand joinCommand = new JoinCommand();
    public MembersCommand membersCommand = new MembersCommand();
    public LeaveCommand leaveCommand = new LeaveCommand();
    public InvitesCommand invitesCommand = new InvitesCommand();
    public ClaimCommand claimCommand = new ClaimCommand();
    public UnClaimCommand unClaimCommand = new UnClaimCommand();
    public UnClaimAllCommand unClaimAllCommand = new UnClaimAllCommand();
    public DescriptionCommand descriptionCommand = new DescriptionCommand();
    public RenameCommand renameCommand = new RenameCommand();
    public MapCommand mapCommand = new MapCommand();
    public InfoCommand infoCommand = new InfoCommand();
    public BypassCommand bypassCommand = new BypassCommand();
    public DeleteCommand deleteCommand = new DeleteCommand();
    public PermissionsCommand permissionsCommand = new PermissionsCommand();
    public KickCommand kickCommand = new KickCommand();
    public PromoteCommand promoteCommand = new PromoteCommand();
    public DemoteCommand demoteCommand = new DemoteCommand();
    public AboutCommand aboutCommand = new AboutCommand();
    public HomeCommand homeCommand = new HomeCommand();
    public SetHomeCommand setHomeCommand = new SetHomeCommand();
    public TransferCommand transferCommand = new TransferCommand();
    public AllyCommand allyCommand = new AllyCommand();
    public EnemyCommand enemyCommand = new EnemyCommand();
    public TruceCommand truceCommand = new TruceCommand();
    public ValueCommand valueCommand = new ValueCommand();
    public TopCommand topCommand = new TopCommand();
    public RecalculateCommand recalculateCommand = new RecalculateCommand();
    public ChatCommand chatCommand = new ChatCommand();
    public WarpsCommand warpsCommand = new WarpsCommand();
    public SetWarpCommand setWarpCommand = new SetWarpCommand();
    public WarpCommand warpCommand = new WarpCommand();
    public DeleteWarpCommand deleteWarpCommand = new DeleteWarpCommand();
    public EditWarpCommand editWarpCommand = new EditWarpCommand();
    public UpgradeCommand upgradeCommand = new UpgradeCommand();
    public ChestCommand chestCommand = new ChestCommand();
    public AccessCommand accessCommand = new AccessCommand();
    public BankCommand bankCommand = new BankCommand();
    public WithdrawCommand withdrawCommand = new WithdrawCommand();
    public DepositCommand depositCommand = new DepositCommand();
}
