name: IridiumFactions
version: ${version}
description: Factions Redefined
main: com.iridium.iridiumfactions.IridiumFactions
api-version: '1.13'
author: Peaches_MLG
depend: [ Vault ]
softdepend:
  - "MVdWPlaceholderAPI"
  - "PlaceholderAPI"
  - "Essentials"
  - "EssentialsSpawn"
  - "RoseStacker"
  - "WorldEdit"
commands:
  iridiumfactions:
    aliases: [ "factions", "f" ]
    description: Main plugin command
